ResearchCollectionsAndPreservation/scsb

src/main/java/org/recap/mqconsumer/RequestItemQueueConsumer.java

commented component

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/DataDumpRestController.java
src/main/resources/application-dev.properties
src/main/resources/application-junit.properties
src/main/resources/application-local-container.properties
src/main/resources/application-local.properties
src/main/resources/application-tst.properties
src/main/resources/application-uat.properties

Added rest controller for data dump

Added rest controller for data dump

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java
src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java

Submit Collection changes

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

RECAP-403 - Added description for input parameter

RECAP-403 - Added description for input parameter

---

build.gradle

Added jacoco plugin for test coverage

Added jacoco plugin for test coverage

---

build.gradle

Added configuration to accept environment variables during execution of junit testcase in jenkins

Added configuration to accept environment variables during execution of junit testcase in jenkins

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

RECAP-462 - Ability to process multiple barcode/customer code during Ongoing Accession

RECAP-462 - Ability to process multiple barcode/customer code during Ongoing Accession

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Added input limit to accession

Added input limit to accession

---

src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java

Fixed the accession UT

---

src/test/java/org/recap/controller/swagger/SharedCollectionRestControllerUT.java

RECAP-488 - Fixed the accession testcase

RECAP-488 - Fixed the accession testcase

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/DataDumpRestController.java

Updated for datadump response code

Updated for datadump response code

---

src/main/java/org/recap/controller/swagger/DataDumpRestController.java
src/main/java/org/recap/controller/swagger/RequestItemRestController.java
src/main/java/org/recap/controller/swagger/SearchRecordsRestController.java
src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Recap530-SwaggerChanges(Edited terms)

Recap530-SwaggerChanges(Edited terms)

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java
src/main/java/org/recap/model/AccessionResponse.java

RECAP-545 - Make json response for Accession service

RECAP-545 - Make json response for Accession service

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/ReportsRestController.java
src/main/java/org/recap/model/IncompleteReportResultsRow.java
src/main/java/org/recap/model/ReportsRequest.java
src/main/java/org/recap/model/ReportsResponse.java

Recap-552 Incomplete Record Report For accession

Recap-552 Incomplete Record Report For accession

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/RequestItemRestController.java
src/main/java/org/recap/model/ItemRequestInformation.java

Recap-530 Modified startPage field and endPage field Type to String

Recap-530 Modified startPage field and endPage field Type to String

---

src/main/java/org/recap/model/DeaccessionItemResultsRow.java

Recap-617 Deaccession report not working for Columbia.

Recap-617 Deaccession report not working for Columbia.

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Changed the URL for deaccession to small letters- RECAP-530 for swagger

Changed the URL for deaccession to small letters- RECAP-530 for swagger

---

src/main/java/org/recap/ReCAPConstants.java
src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Recap-775 Changed error message.

Recap-775 Changed error message.

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Recap-775 Added exception message for scsb solr client service unavailable.

Recap-775 Added exception message for scsb solr client service unavailable

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java
src/main/java/org/recap/model/acession/AccessionResponse.java

Recap-775 Added exception message as AccessionResponseList

Recap-775 Added exception message as AccessionResponseList

---

src/main/java/org/recap/controller/swagger/SharedCollectionRestController.java

Corrected Parameter for accession which was mistakenly modified.

Corrected Parameter for accession which was mistakenly modified.

---

src/main/java/org/recap/config/SwaggerInterceptor.java
src/main/java/org/recap/spring/ApplicationContextProvider.java
src/main/java/org/recap/util/HelperUtil.java
src/main/java/org/recap/util/MD5EncoderUtil.java
src/main/resources/application.properties
src/test/java/org/recap/util/MD5EncoderUtilTest.java

RECAP-840 : Provided the option for the institution to use their own api_key to connect with SCSB.

RECAP-840 : Provided the option for the institution to use their own api_key to connect with SCSB.

---

src/main/java/org/recap/Service/RestHeaderService.java
src/main/java/org/recap/controller/ReportsRestController.java
src/main/java/org/recap/controller/ScheduleJobsController.java
src/main/java/org/recap/controller/UpdateCgdRestController.java
src/main/java/org/recap/controller/swagger/RequestItemRestController.java
src/main/java/org/recap/controller/swagger/SearchRecordsRestController.java
src/main/java/org/recap/spring/PropertyValueProvider.java
src/main/java/org/recap/spring/SwaggerAPIProvider.java
src/main/resources/application.properties
src/test/java/org/recap/controller/ReportsRestControllerUT.java
src/test/java/org/recap/controller/ScheduleJobsControllerUT.java
src/test/java/org/recap/controller/UpdateCgdRestControllerUT.java
src/test/java/org/recap/controller/swagger/RequestItemRestControllerUT.java
src/test/java/org/recap/controller/swagger/SearchRecordsRestControllerUT.java

Recap-867 Removed Hard coded values for swagger api

Recap-867 Removed Hard coded values for swagger api

---

src/main/java/org/recap/model/transfer/ItemTransferRequest.java

Modified for RECAP-833

---

src/main/java/org/recap/controller/swagger/DataDumpRestController.java

Fixed Authentication Issue for scsb-etl Datadump service.

Fixed Authentication Issue for scsb-etl Datadump service.
